version: '3.7'
services:
  database:
    container_name: docker-tamastudy-mysql
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: tamastudy
      MYSQL_USER: the2792
      MYSQL_PASSWORD: canyou12
      MYSQL_ROOT_PASSWORD: canyou12
volumes:
  data: